name: "automate-create_docker_image"

# Триггеры ( = условия), при которых воркфлоу сработает
# В данном случае: на каждый пуш в ветку main
on:
  push:
    branches:
      - 'main'


# Задачи, которые будут выполняться в рамках флоу
jobs:
  # Название задачи, которое будет отображаться в GitHub
  build_and_push:
    # На каком виртуальном сервере будет выполняться задача
    runs-on: ubuntu-latest
    # Шаги выполнения задачи
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          # С каким тегом будет загружен образ
          tags: uralnuthatch/tt_bracket_bot:latest